### PR TITLE
Move to new base16 builder scheme

### PR DESCRIPTION
**Pull request by iamthad**
This creates a default.mustache and config.yaml under templates, and moves the schemes to under windows-command-prompt. Also, the scheme files have been regenerated.

### CODE REVIEW

**Comment by ticky** [comment]
Thank you!

**Comment by iamthad** [comment]
Now that this is merged in, your repo can be added to https://github.com/chriskempson/base16-templates-source so it can be used automatically by base16 builders.

**Comment by ticky** [comment]
I just did the same for [base16-mintty](https://github.com/ticky/base16-mintty/commit/bc4cef21b4ab878783d81e9f146460e70e867c4b), so I guess I can contribute both there!

Only trouble is I don’t actually use Windows for dev anymore, so this isn’t really something whose updates I’m likely to keep up on; would you be interested in taking ownership of it (or them), at all?

**Comment by iamthad** [comment]
Sure, I'd be happy to. I'll credit you as the original template author in the READMEs

**Comment by ticky** [comment]
If you remove your forks of base16-mintty and base16-windows-command-prompt, I can just transfer ownership to you! :smile:

**Comment by iamthad** [comment]
Repos deleted.

**Comment by ticky** [comment]
I’ve sent requests to transfer the repos! Thank you :smile:

**Pull request merged**
